const { escapeHtml: e } = require('./security');
const layout = (title, body, admin=false) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · Obsidian Links</title><link rel="stylesheet" href="/styles.css"></head><body>${admin?`<header><a class="brand" href="/admin">OBSIDIAN<span>LINKS</span></a><nav><a href="/admin">Links</a><a href="/admin/analytics">Analytics</a><form action="/logout" method="post"><button class="ghost">Log out</button></form></nav></header>`:''}<main>${body}</main><script src="/app.js"></script></body></html>`;
const notice = (msg) => msg ? `<p class="notice">${e(msg)}</p>` : '';
function login(error='',preview=false){ return layout('Admin login', `<section class="login card"><p class="eyebrow">Private workspace</p><h1>Welcome back.</h1><p>Manage every destination from one quiet place.</p>${preview?'<div class="preview"><strong>Preview login</strong><code>preview@example.com</code><code>preview123</code></div>':''}${notice(error)}<form method="post"><label>Email<input type="email" name="email" required autocomplete="email"></label><label>Password<input type="password" name="password" required autocomplete="current-password"></label><button>Enter dashboard</button></form></section>`); }
function linkForm(link={}, error='') {
  const editing=Boolean(link.id);
  return layout(editing?'Edit link':'New link', `<div class="pagehead"><div><p class="eyebrow">Smart links</p><h1>${editing?'Edit destination':'Create a smart link'}</h1></div><a class="button ghost" href="/admin">Cancel</a></div><section class="card">${notice(error)}<form method="post" action="${editing?`/admin/links/${link.id}`:'/admin/links'}"><label>Title<input name="title" required maxlength="100" value="${e(link.title)}"></label><label>Slug<div class="prefix"><span>/go/</span><input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value="${e(link.slug)}"></div></label><label>Destination URL<input type="url" name="destination_url" required placeholder="https://example.com" value="${e(link.destination_url)}"></label><label>Source label<input name="source" maxlength="100" placeholder="Instagram bio" value="${e(link.source)}"></label><label class="check"><input type="checkbox" name="is_active" ${link.is_active!==0?'checked':''}> Active</label><button>${editing?'Save changes':'Create link'}</button></form></section>`,true);
}
function dashboard(links, baseUrl) {
  const rows=links.map(l=>`<tr><td><strong>${e(l.title)}</strong><small>${e(l.source)||'No source'}</small></td><td><code>/go/${e(l.slug)}</code></td><td><span class="status ${l.is_active?'on':'off'}">${l.is_active?'Active':'Inactive'}</span></td><td>${l.clicks}</td><td class="actions"><button class="copy ghost" data-copy="${e(baseUrl)}/go/${e(l.slug)}">Copy</button><a href="/admin/links/${l.id}/edit">Edit</a><form action="/admin/links/${l.id}/toggle" method="post"><button class="ghost">${l.is_active?'Pause':'Activate'}</button></form><form action="/admin/links/${l.id}/delete" method="post" data-confirm="Delete this link and its analytics?"><button class="danger ghost">Delete</button></form></td></tr>`).join('');
  return layout('Dashboard', `<div class="pagehead"><div><p class="eyebrow">Command center</p><h1>Your smart links</h1><p>Create clean redirects now. Add deeper routing later.</p></div><a class="button" href="/admin/links/new">+ New smart link</a></div><section class="card tablewrap"><table><thead><tr><th>Link</th><th>Path</th><th>Status</th><th>Clicks</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="5" class="empty">No links yet. Create your first smart link.</td></tr>'}</tbody></table></section>`,true);
}
const panel=(title,items)=>`<section class="card panel"><h2>${e(title)}</h2>${items.length?items.map(x=>`<div class="metric"><span>${e(x.label)}</span><strong>${x.value}</strong><i style="width:${Math.min(100,x.value*5)}%"></i></div>`).join(''):'<p class="muted">No data yet.</p>'}</section>`;
function analytics(a){ return layout('Analytics', `<div class="pagehead"><div><p class="eyebrow">Signal room</p><h1>Analytics</h1><p>Privacy-conscious insights. Raw IP addresses are never stored.</p></div></div><div class="stats"><section class="card"><span>Total clicks</span><strong>${a.total}</strong></section><section class="card"><span>Unique visitors</span><strong>${a.unique}</strong></section></div><div class="grid">${panel('Clicks by day',a.days)}${panel('Clicks by link',a.byLink)}${panel('Clicks by source',a.bySource)}${panel('Devices',a.devices)}${panel('Browsers',a.browsers)}${panel('Operating systems',a.systems)}${panel('In-app browsers',a.inApps)}${panel('Top referrers',a.referrers)}${panel('UTM source',a.utmSource)}${panel('UTM medium',a.utmMedium)}${panel('UTM campaign',a.utmCampaign)}</div>`,true); }
module.exports={login,linkForm,dashboard,analytics};
